# Traefik reverse proxy container
#
# TLS-terminating reverse proxy for infrastructure services.
# Uses host networking so it can bind ports 80/443 directly on the VM's IP.
#
# TLS certs and static config are generated by Nix.  Service routers
# (Host rules, backends) are written at runtime by the service-monitor
# into a watched dynamic config directory.
# A self-signed certificate is generated on first boot and persisted in
# /var/lib/traefik/certs/ so it can be pinned by clients.

{ config, lib, pkgs, ... }:

let
  cfg = config.services.nifty-services;
  traefikCfg = cfg.traefik;

  useAcme = traefikCfg.tls.acmeUrl != null;

  # TLS certificate config — must live in Traefik's dynamic config (not static).
  # Only used in self-signed mode; ACME mode uses certificatesResolvers instead.
  tlsConfig = {
    tls.certificates = [
      {
        certFile = "/certs/traefik.crt";
        keyFile = "/certs/traefik.key";
      }
    ];
  };

  tlsConfigFile = pkgs.writeText "traefik-tls.yml"
    (builtins.toJSON tlsConfig);

  # Static traefik config
  staticConfig = {
    entryPoints = {
      web = {
        address = ":80";
        http.redirections.entryPoint = {
          to = "websecure";
          scheme = "https";
        };
      };
      websecure = {
        address = ":443";
      } // lib.optionalAttrs useAcme {
        http.tls.certResolver = "step-ca";
      };
    } // lib.optionalAttrs traefikCfg.dashboard.enable {
      traefik = {
        address = ":${toString traefikCfg.dashboard.port}";
      };
    };
    providers.file = {
      directory = "/etc/traefik/dynamic";
      watch = true;
    };
    log.level = traefikCfg.logLevel;
  } // lib.optionalAttrs traefikCfg.dashboard.enable {
    api = {
      dashboard = true;
      insecure = true;
    };
  } // lib.optionalAttrs useAcme {
    certificatesResolvers.step-ca.acme = {
      caServer = traefikCfg.tls.acmeUrl;
      storage = "/acme/acme.json";
      tlsChallenge = {};
    };
  };

  staticConfigFile = pkgs.writeText "traefik.yml"
    (builtins.toJSON staticConfig);

  certDir = "/var/lib/traefik/certs";
  acmeDir = "/var/lib/traefik/acme";
in
{
  options.services.nifty-services.traefik = {
    enable = lib.mkEnableOption "Traefik reverse proxy container";

    image = lib.mkOption {
      type = lib.types.str;
      default = "docker.io/traefik:v3";
      description = "Container image for the Traefik reverse proxy.";
    };

    logLevel = lib.mkOption {
      type = lib.types.enum [ "DEBUG" "INFO" "WARN" "ERROR" ];
      default = "INFO";
      description = "Traefik log level.";
    };

    dashboard = {
      enable = lib.mkEnableOption "Traefik dashboard (insecure, for local use only)";

      port = lib.mkOption {
        type = lib.types.port;
        default = 8080;
        description = "Port for the Traefik dashboard.";
      };
    };

    tls = {
      acmeUrl = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        example = "https://10.99.2.3:9443/acme/acme/directory";
        description = "Step-CA ACME directory URL. When set, Traefik uses ACME instead of self-signed certs.";
      };

      caCertPath = lib.mkOption {
        type = lib.types.nullOr lib.types.path;
        default = null;
        description = "Path to Step-CA root cert on the host (for LEGO_CA_CERTIFICATES).";
      };
    };

    cert = {
      subject = lib.mkOption {
        type = lib.types.str;
        default = "/CN=infra-services";
        description = "Subject for the self-signed TLS certificate (only used when tls.acmeUrl is null).";
      };

      days = lib.mkOption {
        type = lib.types.int;
        default = 3650;
        description = "Validity period in days for the self-signed certificate.";
      };

      san = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [];
        example = [ "DNS:nifty.internal" "IP:10.99.2.2" ];
        description = "Subject Alternative Names for the self-signed certificate.";
      };
    };

    # Service routers (e.g. technitium) are managed dynamically by the
    # service-monitor via the watched dynamic config directory.
  };

  config = lib.mkIf (cfg.enable && traefikCfg.enable) {
    # Generate self-signed certificate on first boot, persist in /var.
    # Only used when ACME is not configured.
    systemd.services.traefik-selfsign-cert = lib.mkIf (!useAcme) {
      description = "Generate self-signed TLS certificate for Traefik";
      wantedBy = [ "multi-user.target" ];
      before = [ "podman-traefik.service" ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };
      path = [ pkgs.openssl ];
      script = let
        sanArg = lib.optionalString (traefikCfg.cert.san != [])
          "-addext 'subjectAltName=${lib.concatStringsSep "," traefikCfg.cert.san}'";
      in ''
        mkdir -p ${certDir}
        if [ ! -f ${certDir}/traefik.key ]; then
          echo "Generating self-signed certificate..."
          openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:prime256v1 \
            -keyout ${certDir}/traefik.key \
            -out ${certDir}/traefik.crt \
            -days ${toString traefikCfg.cert.days} \
            -nodes \
            -subj '${traefikCfg.cert.subject}' \
            ${sanArg}
          echo "Certificate generated at ${certDir}/"
        else
          echo "Certificate already exists, skipping generation."
        fi
      '';
    };

    # Seed the traefik-dynamic volume with TLS certificate references (self-signed only)
    # and clean up stale files. Service-monitor writes route-*.yml at runtime.
    systemd.services.traefik-seed-dynamic = {
      description = "Seed Traefik dynamic config volume";
      wantedBy = [ "multi-user.target" ];
      before = [ "podman-traefik.service" ];
      after = (lib.optional (!useAcme) "traefik-selfsign-cert.service")
        ++ [ "podman-volumes.service" ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };
      path = [ pkgs.podman ];
      script = ''
        podman volume exists traefik-dynamic || podman volume create traefik-dynamic
        MOUNT=$(podman volume inspect traefik-dynamic --format '{{.Mountpoint}}')
        ${if useAcme then ''
          # ACME mode: remove tls.yml if left over from self-signed mode
          rm -f "$MOUNT/tls.yml"
        '' else ''
          cp ${tlsConfigFile} "$MOUNT/tls.yml"
        ''}
        # Clean up stale files — only tls.yml and route-*.yml are managed
        for f in "$MOUNT"/*.yml; do
          [ -f "$f" ] || continue
          base=$(basename "$f")
          case "$base" in
            tls.yml|route-*.yml) ;;
            *) echo "Removing stale dynamic config: $base"; rm -f "$f" ;;
          esac
        done
      '';
    };

    # Create ACME state directory for Traefik (ACME mode only)
    systemd.services.traefik-acme-dir = lib.mkIf useAcme {
      description = "Create Traefik ACME state directory";
      wantedBy = [ "multi-user.target" ];
      before = [ "podman-traefik.service" ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };
      script = ''
        mkdir -p ${acmeDir}
        chmod 700 ${acmeDir}
      '';
    };

    virtualisation.oci-containers.backend = "podman";
    virtualisation.oci-containers.containers.traefik = {
      image = traefikCfg.image;
      volumes = [
        "${staticConfigFile}:/etc/traefik/traefik.yml:ro"
        "traefik-dynamic:/etc/traefik/dynamic:ro"
      ] ++ (if useAcme then [
        "${acmeDir}:/acme"
      ] ++ lib.optional (traefikCfg.tls.caCertPath != null)
        "${traefikCfg.tls.caCertPath}:/etc/ssl/step-ca-root.crt:ro"
      else [
        "${certDir}:/certs:ro"
      ]);
      environment = lib.optionalAttrs (useAcme && traefikCfg.tls.caCertPath != null) {
        LEGO_CA_CERTIFICATES = "/etc/ssl/step-ca-root.crt";
      };
      extraOptions = [
        "--network=host"
      ];
      dependsOn = [];
    };

    # Ensure cert/config seeding runs before traefik starts
    systemd.services.podman-traefik = {
      after = (lib.optional (!useAcme) "traefik-selfsign-cert.service")
        ++ (lib.optional useAcme "traefik-acme-dir.service")
        ++ [ "traefik-seed-dynamic.service" ];
      requires = (lib.optional (!useAcme) "traefik-selfsign-cert.service")
        ++ (lib.optional useAcme "traefik-acme-dir.service")
        ++ [ "traefik-seed-dynamic.service" ];
    };

    networking.firewall.allowedTCPPorts = [ 80 443 ]
      ++ lib.optional traefikCfg.dashboard.enable traefikCfg.dashboard.port;
  };
}
