# Traefik reverse proxy container
#
# TLS-terminating reverse proxy for infrastructure services.
# Uses host networking so it can bind ports 80/443 directly on the VM's IP.
#
# TLS certs and static config are generated by Nix.  Service routers
# (Host rules, backends) are written at runtime by the service-monitor
# into a watched dynamic config directory.
# A self-signed certificate is generated on first boot and persisted in
# /var/lib/traefik/certs/ so it can be pinned by clients.

{ config, lib, pkgs, ... }:

let
  cfg = config.services.nifty-services;
  traefikCfg = cfg.traefik;

  # TLS certificate config — must live in Traefik's dynamic config (not static).
  # Service routers are written at runtime by the service-monitor.
  tlsConfig = {
    tls.certificates = [
      {
        certFile = "/certs/traefik.crt";
        keyFile = "/certs/traefik.key";
      }
    ];
  };

  tlsConfigFile = pkgs.writeText "traefik-tls.yml"
    (builtins.toJSON tlsConfig);

  # Static traefik config
  staticConfig = {
    entryPoints = {
      web = {
        address = ":80";
        http.redirections.entryPoint = {
          to = "websecure";
          scheme = "https";
        };
      };
      websecure = {
        address = ":443";
      };
    } // lib.optionalAttrs traefikCfg.dashboard.enable {
      traefik = {
        address = ":${toString traefikCfg.dashboard.port}";
      };
    };
    providers.file = {
      directory = "/etc/traefik/dynamic";
      watch = true;
    };
    log.level = traefikCfg.logLevel;
  } // lib.optionalAttrs traefikCfg.dashboard.enable {
    api = {
      dashboard = true;
      insecure = true;
    };
  };

  staticConfigFile = pkgs.writeText "traefik.yml"
    (builtins.toJSON staticConfig);

  certDir = "/var/lib/traefik/certs";
in
{
  options.services.nifty-services.traefik = {
    enable = lib.mkEnableOption "Traefik reverse proxy container";

    image = lib.mkOption {
      type = lib.types.str;
      default = "docker.io/traefik:v3";
      description = "Container image for the Traefik reverse proxy.";
    };

    logLevel = lib.mkOption {
      type = lib.types.enum [ "DEBUG" "INFO" "WARN" "ERROR" ];
      default = "INFO";
      description = "Traefik log level.";
    };

    dashboard = {
      enable = lib.mkEnableOption "Traefik dashboard (insecure, for local use only)";

      port = lib.mkOption {
        type = lib.types.port;
        default = 8080;
        description = "Port for the Traefik dashboard.";
      };
    };

    cert = {
      subject = lib.mkOption {
        type = lib.types.str;
        default = "/CN=infra-services";
        description = "Subject for the self-signed TLS certificate.";
      };

      days = lib.mkOption {
        type = lib.types.int;
        default = 3650;
        description = "Validity period in days for the self-signed certificate.";
      };

      san = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [];
        example = [ "DNS:nifty.internal" "IP:10.99.2.2" ];
        description = "Subject Alternative Names for the self-signed certificate.";
      };
    };

    # Service routers (e.g. technitium) are managed dynamically by the
    # service-monitor via the watched dynamic config directory.
  };

  config = lib.mkIf (cfg.enable && traefikCfg.enable) {
    # Generate self-signed certificate on first boot, persist in /var
    systemd.services.traefik-selfsign-cert = {
      description = "Generate self-signed TLS certificate for Traefik";
      wantedBy = [ "multi-user.target" ];
      before = [ "podman-traefik.service" ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };
      path = [ pkgs.openssl ];
      script = let
        sanArg = lib.optionalString (traefikCfg.cert.san != [])
          "-addext 'subjectAltName=${lib.concatStringsSep "," traefikCfg.cert.san}'";
      in ''
        mkdir -p ${certDir}
        if [ ! -f ${certDir}/traefik.key ]; then
          echo "Generating self-signed certificate..."
          openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:prime256v1 \
            -keyout ${certDir}/traefik.key \
            -out ${certDir}/traefik.crt \
            -days ${toString traefikCfg.cert.days} \
            -nodes \
            -subj '${traefikCfg.cert.subject}' \
            ${sanArg}
          echo "Certificate generated at ${certDir}/"
        else
          echo "Certificate already exists, skipping generation."
        fi
      '';
    };

    # Seed the traefik-dynamic volume with TLS certificate references.
    # Service-monitor writes router configs into the same volume at runtime.
    systemd.services.traefik-seed-dynamic = {
      description = "Seed Traefik dynamic config volume with TLS config";
      wantedBy = [ "multi-user.target" ];
      before = [ "podman-traefik.service" ];
      after = [ "traefik-selfsign-cert.service" "podman-volumes.service" ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };
      path = [ pkgs.podman ];
      script = ''
        podman volume exists traefik-dynamic || podman volume create traefik-dynamic
        MOUNT=$(podman volume inspect traefik-dynamic --format '{{.Mountpoint}}')
        cp ${tlsConfigFile} "$MOUNT/tls.yml"
        # Clean up stale files — only tls.yml and route-*.yml are managed
        for f in "$MOUNT"/*.yml; do
          [ -f "$f" ] || continue
          base=$(basename "$f")
          case "$base" in
            tls.yml|route-*.yml) ;;
            *) echo "Removing stale dynamic config: $base"; rm -f "$f" ;;
          esac
        done
      '';
    };

    virtualisation.oci-containers.backend = "podman";
    virtualisation.oci-containers.containers.traefik = {
      image = traefikCfg.image;
      volumes = [
        "${staticConfigFile}:/etc/traefik/traefik.yml:ro"
        "traefik-dynamic:/etc/traefik/dynamic:ro"
        "${certDir}:/certs:ro"
      ];
      extraOptions = [
        "--network=host"
      ];
      dependsOn = [];
    };

    # Ensure cert and dynamic config seeding run before traefik starts
    systemd.services.podman-traefik = {
      after = [ "traefik-selfsign-cert.service" "traefik-seed-dynamic.service" ];
      requires = [ "traefik-selfsign-cert.service" "traefik-seed-dynamic.service" ];
    };

    networking.firewall.allowedTCPPorts = [ 80 443 ]
      ++ lib.optional traefikCfg.dashboard.enable traefikCfg.dashboard.port;
  };
}
